# Generated by Django 4.1.3 on 2022-12-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_contactinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.contactinformation', verbose_name='User profile'),
        ),
    ]
