# Generated by Django 4.1.3 on 2022-12-13 18:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_contactinformation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='User phone number'),
        ),
    ]
