version: "3.9"

services:

  shopping_cart_api:
    build: .
    image: shopping_cart_api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: [
      "-p", "${POSTGRES_PORT}",
    ]
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "GUNICORN_ACCESS_LOGFILE=/dev/null"
      - "PGADMIN_DEFAULT_EMAIL=dev@dev.com"
      - "PGADMIN_DEFAULT_PASSWORD=devdev"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  database:
  pgadmin: