# Generated by Django 4.1.3 on 2022-12-13 18:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_cart', '0004_shoppingcart_products_alter_orderedproduct_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Is ordered'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='shopping_cart.shoppingcart', verbose_name='Shopping cart'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='products.product', verbose_name='Product in order'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Customer phone number')),
                ('delivery_place', models.CharField(max_length=32, verbose_name='Place to deliver order')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='shopping_cart.shoppingcart', verbose_name='Cart with products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
